### ISSUE TITLE
What is QAMFace?

### ISSUE THREAD

**Issue by fuxuliu** [MccreeZhao/FR-Loss-on-Mnist#3]
hi, could you share the paper about QAMFace? thank you.

**Comment by MccreeZhao** [comment]
Hi, thanks for your attention. 

Our paper is still under review. If the paper is accepted or we decide to upload it to Arxiv, we will let you know. 

By the way, you could try to use QAMFace in your tasks first, it performs better than ArcFace according to our experiment results.

**Comment by fuxuliu** [comment]
@MccreeZhao oh, thanks your reply, could you share the full title about QAMFace?
yep, I will try it.

**Comment by MccreeZhao** [comment]
https://github.com/MccreeZhao/QAMFace
